### ISSUE TITLE
Recipes to cook Optee kernel and optee-examples in qemu image

### ISSUE THREAD

**Issue by neithanmo** [Zondax/meta-zondax-qemu#3]
a minimal image build with yocto must come with updated and board-wise compatible optee drivers and the official optee examples. support for qemu_v8 is required.

**Comment by keyfour** [comment]
## Description

Brarch: [hardknott](https://github.com/Zondax/meta-zondax-qemu/tree/hardknott)
Revision: [89391399ca4a26a5e3c0c009b4aa687272ba38db](https://github.com/Zondax/meta-zondax-qemu/tree/89391399ca4a26a5e3c0c009b4aa687272ba38db)

- Updated dependencies and recipes to run `optee-os` v3.14.0 and `linux-optee` v.5.13.0.
- Clean recipes and remove redundant dependencies
- Add patch to fix issue with memory management on the `qemu8` target

OPTEE examples added in another [layer](https://github.com/Zondax/meta-zondax/tree/dev) .

## How has this been tested?

Using [tee-images](https://github.com/Zondax/tee-images) dev environment:

### Qemu 32 bit
```bash
make build qemu
make dev qemu
```
### Qemu 64 bit
```bash
make build qemu8
make dev qemu8
```

OPTEE examples are place in: `/usr/bin`:

- `optee_example_acipher`
- `optee_example_aes`
- `optee_example_hello_world`
- `optee_example_hotp`
- `optee_example_plugins`
- `optee_example_random`
- `optee_example_secure_storage`

### Results
- `xtest` runs successfully
- OPTEE examples run successfully

## Screenshots
![xtest_success_screeshot](https://user-images.githubusercontent.com/10725294/133249270-472255a2-014c-481e-8991-e6ab08d29d96.png)

![examples_screenshot](https://user-images.githubusercontent.com/10725294/133249643-b0d66a47-9217-4f1b-a355-65239a19b096.png)

**Comment by neithanmo** [comment]
great !!!.. I was also able to run the test and it works
