### ISSUE TITLE
Integrate the hello-rustee example

### ISSUE THREAD

**Issue by neithanmo** [Zondax/meta-zondax-qemu#5]
The final image should come with the hello-rustee example, this example can be found [here](https://github.com/Zondax/hello-rustee/tree/simple_tee) which is a really simple example but good enough as it does not require any dependencies. it is possible that a real application may require more dependencies that's why it should be easier to modify recipes to include them(development target, using qemu).

**Comment by neithanmo** [comment]
as an update, the hello-rustee(simple_tee branch) example is outdated although functional. it will be updated or replaced by tee-substrate-service

**Comment by neithanmo** [comment]
Another important thing about integrating the hello-rustee app is that it should be run add boot-time. as a real application may start a jsonrpc/tcp/http service(The RRE part that runs on the host).

**Comment by keyfour** [comment]
@neithanmo hello-rustee app works on both qemu versions (32/64 bit).
